Repository neonadeuri/reviewer-reviewee-frontend, pull requests merged in 2023-04, with the labels that each got.

#42 [#39] 리뷰 상세정보 모달 API 구현 및 연결
  components/ButtonWrapper.tsx
  components/Main/ReviewerCard.tsx
  components/ReviewListSearch/ReviewInquireBox.tsx
  components/ReviewModal/ReviewModal.tsx
  components/ReviewModal/ReviewModifyLink.tsx
  components/ReviewModal/ReviewSection.tsx
  components/ReviewModal/reviewModalType.ts
  mocks/handlers.ts
  pages/api/inquire.ts
  pages/index.tsx
Labels: 🚀 feature, 🛠 refactor

#44 [#41] 리뷰 수락 및 거절 기능 구현
  components/ButtonWrapper.tsx
  components/ReviewListSearch/queries/getReviewsQuery.tsx
  components/ReviewModal/ReviewModal.tsx
  mocks/handlers.ts
  pages/api/inquire.ts
Labels: 🚀 feature

#45 [#43] 리뷰 신청 페이지 에디터 에러 멘트 로직 수정 및 통합관리로 수정 작업
  components/Header.tsx
  components/HeaderSub/GithubLogInButton.tsx
  components/HeaderSub/HeaderDropDown.tsx
  components/Loading.tsx
  components/Main/CategoryTagButton.tsx
  components/Main/FilterCategory.tsx
  components/Main/PickTagCard.tsx
  components/Main/ReviewerCard.tsx
  components/ReviewListSearch/ReviewInquireBox.tsx
  components/ReviewListSearch/ReviewRoleButtonGroup.tsx
  components/ReviewModal/ReviewModal.tsx
  components/ReviewModal/ReviewModifyLink.tsx
  components/ReviewRegister/ErrorMent.tsx
  components/ReviewRegister/RegisterForm.tsx
  components/ReviewRegister/ReviewEditor.tsx
  components/ReviewRegister/ReviewRegisterType.ts
  components/userInfomation/HookFormDropDown.tsx
  components/userInfomation/InformationForm.tsx
  components/userInfomation/ReviewerRegisterModal.tsx
  components/userInfomation/UserInput.tsx
  tailwind.config.js
Labels: 🛠 refactor

#48 [#47] withCredential 추가 및 폴더명 수정
  atoms/userState.ts
  components/UserInformation/HookFormDropDown.tsx
  components/UserInformation/InformationForm.tsx
  components/UserInformation/InformationTemplate.tsx
  components/UserInformation/ReviewerDropDown.tsx
  components/UserInformation/ReviewerRegisterModal.tsx
  components/UserInformation/UserInput.tsx
  components/UserInformation/informationType.ts
  mocks/handlers.ts
  pages/api/member.ts
  pages/api/reviewRegister.ts
  pages/api/userInfo.ts
  pages/user/me.tsx
Labels: 🛠 refactor

#52 [#50] 로그아웃 기능 연동
  components/HeaderSub/HeaderDropDown.tsx
  components/ReviewListSearch/Template.tsx
  components/ReviewRegister/ReviewRegisterTemplate.tsx
  components/UserInformation/InformationTemplate.tsx
Labels: 🚀 feature

#53 [#51] 리뷰어 활동 여부 로직 개선
  atoms/userState.ts
  components/UserInformation/InformationForm.tsx
  components/UserInformation/InformationTemplate.tsx
  components/UserInformation/informationType.ts
  pages/api/member.ts
Labels: 🛠 refactor

#55 [#54] 마이 페이지 스타일 리팩토링
  components/ButtonWrapper.tsx
  components/UserInformation/HookFormDropDown.tsx
  components/UserInformation/InformationForm.tsx
  components/UserInformation/InformationTemplate.tsx
  components/UserInformation/ReviewerRegisterModal.tsx
  components/UserInformation/UserInput.tsx
  globalType.ts
Labels: 🛠 refactor

#58 [#57] 카테고리 및 태그 SSR 변경
  components/Main/Template.tsx
  pages/api/main.ts
  pages/index.tsx
Labels: 🛠 refactor

#61 [#59] 메인 페이지 UI 수정
  components/Header.tsx
  components/HeaderSub/HeaderDropDown.tsx
  components/Main/ReviewerCard.tsx
  components/Main/Template.tsx
  tailwind.config.js
Labels: 🛠 refactor

#62 [#60] 마이 페이지 모달 드롭다운 컴포넌트 분리
  atoms/userState.ts
  components/ReviewModal/ReviewModal.tsx
  components/ReviewModal/queries/getReviewModalQuery.tsx
  components/UserInformation/HookFormDropDown.tsx
  components/UserInformation/InformationForm.tsx
  components/UserInformation/ReviewModalDropDownSelect.tsx
  components/UserInformation/ReviewModalDropDownSkill.tsx
  components/UserInformation/ReviewerDropDown.tsx
  components/UserInformation/ReviewerRegisterModal.tsx
  components/UserInformation/informationType.ts
  components/UserInformation/queries/getReviewerQuery.tsx
  pages/api/member.ts
Labels: 🛠 refactor

#64 [#63] 리뷰 작성 에디터 렌더링 개선
  components/ReviewRegister/ErrorMent.tsx
  components/ReviewRegister/RegisterForm.tsx
  components/ReviewRegister/ReviewEditor.tsx
  components/ReviewRegister/ReviewRegisterType.ts
Labels: 🛠 refactor

#67 [#66] Index Page SSR 내 Msw 서버 문제 해결
  pages/index.tsx
Labels: 🛠 refactor
